# fly.toml app configuration file generated for tedyeates on 2023-08-15T13:27:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tedyeates"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
